// Auto-generated from Python ViewerConfig defaults. Do not edit manually.
// Regenerated by mjswan._build_client.ClientBuilder.generate_viewer_config_defaults()

export const VIEWER_CONFIG_DEFAULTS = {
  lookat: [0.0, 0.0, 0.3] as [number, number, number],
  distance: 2.5,
  elevation: -20.0,
  azimuth: 180.0,
  fovy: 45,
  originType: 'AUTO' as const,
  enableReflections: true,
  enableShadows: true,
  height: 240,
  width: 320,
} as const;
